### ISSUE TITLE
Пригоден ли  API у BoxBerry для частных пользователей (не ИП)?

### ISSUE THREAD

**Issue by mediaexplorer74** [Varkentin/BoxberryClient#1]
Здравствуйте. Интересная библиотека. Спасибо за Ваш труд. Тема заинтересовала, так как имею нестандартный моб. тел (Люмка 950), где туговато с современными приложениями типа Boxberry.. Но есть одно НО: не могу получить токен, так как я просто человек, не ИП и т.д. Стало быть, API у BoxBerry для частных пользователей непригоден? Что интересно, в примерах из их документации по API BoxBerry, ссыль на которую Вы любезно в readme привели, есть некий демо-токен. Он вроде отрабатывает какие то не особо нужные мне запросы вроде шкалы цен: 
https://api.boxberry.ru/json.php?token=d6f33e419c16131e5325cbd84d5d6000&method=DeliveryCosts&weight=500&targetstart=010&target=010&ordersum=0&deliverysum=0&height=120&width=80&depth=50&paysum=100
Успех: {"price":204.6,"price_base":126,"price_service":78.6,"delivery_period":"1"}
 Но если я пытаюсь трекнуть собств. посылку ценным для меня запросом (ну, чтобы потом в приложении нотификацию сделать, что пора бежать на почту посылочку забирать)) типа такого
 https://api.boxberry.ru/json.php?method=ListStatuses&token=d6f33e419c16131e5325cbd84d5d6000&ImId=XXXXXX
 , он ни черта не отдает при любых моих вводных XXXXXX (пробовал и номер заказа, и ид трека):
{"err":"Не найдено данных по указанному параметру ImId."}
 
 
  А жаль, т.к. люди вполне бы могли какую-нить годноту закодить под всякие Tizen и прочие умные девайсы...  Ну или даж Xamarin Forms или демона MAUI призвать для реальной кросс-платформы =)
  
Буду рад, если как-то подтолкнете. Мож, у Вас есть какой-нить ненужный api токен или связи с инженерами Boxberry? Вот б их кто натолкнул на мысль, что API надо не токо для интеграций с и-магами..

С уважением,
MediaExplorer74

**Comment by Varkentin** [comment]
Салют, попробуйте написать в их тп) скорее всего нужно будет заключать договор
по поводу вашей ошибки:
он задается при создании заказа https://help.boxberry.ru/pages/viewpage.action?pageId=763005
 ImId - код отслеживания заказа или номер заказа ИМ.
